name: emobilepro
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.61+62

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  get:
  hexcolor:
  font_awesome_flutter:
  flutter_screenutil:
  http:
  path_provider:
  sqflite:
  dropdown_button2:
  salomon_bottom_bar:
  fluttertoast:
  flutter_search_bar:
  dio:
  flutter_easyloading:
  share_plus:
  pdf:
  pdf_image_renderer:
  open_filex:
  uuid:
  hive_flutter:
  device_info_plus:
  permission_handler:
  file_picker:
  device_name:
  unique_identifier:
  image_picker:
  network_info_plus:
  syncfusion_flutter_datagrid:
  esc_pos_printer:
  #flutter_pos_printer_platform_image_3:
  flutter_blue_plus:
  esc_pos_utils:

#  esc_pos_bluetooth:
#  bluetooth_print:
#  bluetooth_thermal_printer:
  blue_thermal_printer:
  syncfusion_flutter_pdfviewer:
  pull_to_refresh:
  number_to_character:
  barcode_scan2: ^4.5.1
#  flutter_barcode_scanner:
  number_to_word_arabic:
  flutter_background_service: ^5.0.10
  flutter_local_notifications:
  shared_preferences:
  simple_animations:
#  charts_flutter:
  geolocator:
  fl_chart:
  upgrader:
  signature:
  url_launcher: ^6.1.10
#  contacts_service:
  flutter_speed_dial:
  lucide_icons:
  marquee:
  syncfusion_flutter_charts:
  flutter_launcher_icons:
  cupertino_icons:
  isar:
  flutter_pos_printer_platform_image_3:
  #isar_flutter_libs:

    #Windows-specific implementations
  path_provider_windows:
  flutter_local_notifications_windows:
  #sqflite_common_ffi:
  image_picker_windows:
  sqlite3_flutter_libs:   # تضمين مكتبة SQLite الأصلية على Windows
  sqflite_common_ffi:     # واجهة FFI لـ sqflite على Desktop

    #Windows-specific implementations
  sqflite_common_ffi_web:
  flutter_spinkit:
  logger:
  getwidget:
  workmanager:
  infinite_scroll_pagination: 4.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  isar_generator:        # لتوليد الكود
  build_runner:          # لتشغيل البناء

dependency_overrides:
  #image: "3.3.0"  # Or any version that fits your needs
  #pdf: "3.8.4"
  # flutter_scan_bluetooth:
  #   path: ./projects/flutter_scan_bluetooth/
  # imin_printer:
  #   path: ./projects/imin_printer/
  dropdown_search:
#  flutter_pos_printer_platform_image_3_pk:
#    path: ./Packages/flutter_pos_printer_platform/


flutter_icons:
  android: true
  ios: true
  image_path: "Assets/image/EMobile Pro.jpg"
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - Assets/image/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Hacen
      fonts:
        - asset: Assets/fonts/HacenTunisia.ttf
          #    - asset: Assets/fonts/Hacen_Tunisia_Bold.ttf
          weight: 700
    - family: Rubik
      fonts:
        - asset: Assets/fonts/Rubik-Regular.otf
          weight: 700
    - family: Sar
      fonts:
        - asset: Assets/fonts/NewRiyal-Regular.ttf
          weight: 700
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
